# Generated by Django 4.2.16 on 2024-09-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_template_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
