# Generated by Django 4.2.16 on 2024-09-27 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute_library', '0001_initial'),
        ('data_template_engine', '0002_alter_datatemplate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_mappings', to='attribute_library.field')),
                ('source_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='attribute_library.field')),
            ],
        ),
        migrations.AlterField(
            model_name='datatemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='DataTemplateMapping',
        ),
        migrations.AddField(
            model_name='fieldmapping',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='data_template_engine.datatemplate'),
        ),
    ]
