# Generated by Django 4.2.16 on 2024-09-29 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_template_engine', '0003_fieldmapping_alter_datatemplate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmapping',
            name='parent_mapping',
            field=models.ForeignKey(blank=True, help_text='Self-reference for nested mappings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='data_template_engine.fieldmapping'),
        ),
    ]
