# Generated by Django 4.2.16 on 2024-09-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('visible_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=50)),
            ],
        ),
    ]
